// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// hello //
// ----- //

#define hello_wrap_target 0
#define hello_wrap 6
#define hello_pio_version 0

static const uint16_t hello_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, ~null
    0x00c3, //  1: jmp    pin, 3
    0x0001, //  2: jmp    1
    0x4021, //  3: in     x, 1
    0x00c4, //  4: jmp    pin, 4
    0x4061, //  5: in     null, 1
    0x0001, //  6: jmp    1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hello_program = {
    .instructions = hello_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = hello_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hello_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hello_wrap_target, offset + hello_wrap);
    return c;
}

static inline void hello_program_init(PIO pio, uint sm, uint offset, uint input_pin) {
    pio_sm_config c = hello_program_get_default_config(offset);
    pio_gpio_init(pio, input_pin);
    //set up the jump pin to be using input_pin
    sm_config_set_jmp_pin(&c, input_pin);
    //setup autopull and autopush
    sm_config_set_out_shift(&c, false, true, 32); //false, true here means shift MSB out first and autopush enabled
    sm_config_set_in_shift(&c, false, true, 32);
    //sm_config_set_out_pins(&c, input_pin, 1);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_consecutive_pindirs(pio, sm, input_pin, 1, false);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif

